linters:
  enable:
  - errcheck
  - goconst
  - gofmt
  - revive
  - gosec
  - govet
  - ineffassign
  - lll
  - gosimple
  - staticcheck
  - unused
  - misspell
  - nakedret
  - unconvert
  enable-all: false
linters-settings:
  lll:
    line-length: 130
issues:
  exclude-files:
  - schema.go
  - pulumiManifest.go
  - doc.go
run:
  timeout: 20m
