archives:
- id: archive
  name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
before:
  hooks:
  - make tfgen
blobs:
- bucket: pulumi-fusionauth
  folder: releases/plugins/
  ids:
  - archive
  provider: s3
  region: us-east-1
builds:
- binary: pulumi-resource-pulumi-fusionauth
  dir: provider
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - windows
  - linux
  ignore: []
  ldflags:
  - -X
    github.com/theogravity/pulumi-fusionauth/provider/v2/pkg/version.Version={{.Tag}}
  main: ./cmd/pulumi-resource-fusionauth/
changelog:
  skip: true
release:
  disable: true
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
