// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace theogravity.Fusionauth
{
    [FusionauthResourceType("fusionauth:index/fusionAuthEntityTypePermission:FusionAuthEntityTypePermission")]
    public partial class FusionAuthEntityTypePermission : global::Pulumi.CustomResource
    {
        /// <summary>
        /// An object that can hold any information about the Permission that should be persisted. Must be a JSON string.
        /// </summary>
        [Output("data")]
        public Output<string?> Data { get; private set; } = null!;

        /// <summary>
        /// The description of the Permission.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The Id of the Entity Type.
        /// </summary>
        [Output("entityTypeId")]
        public Output<string> EntityTypeId { get; private set; } = null!;

        /// <summary>
        /// Whether or not the Permission is a default permission. A default permission is automatically granted to an entity of
        /// this type if no permissions are provided in a grant request.
        /// </summary>
        [Output("isDefault")]
        public Output<bool?> IsDefault { get; private set; } = null!;

        /// <summary>
        /// The name of the Permission.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The Id to use for the new permission. If not specified a secure random UUID will be generated.
        /// </summary>
        [Output("permissionId")]
        public Output<string> PermissionId { get; private set; } = null!;


        /// <summary>
        /// Create a FusionAuthEntityTypePermission resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public FusionAuthEntityTypePermission(string name, FusionAuthEntityTypePermissionArgs args, CustomResourceOptions? options = null)
            : base("fusionauth:index/fusionAuthEntityTypePermission:FusionAuthEntityTypePermission", name, args ?? new FusionAuthEntityTypePermissionArgs(), MakeResourceOptions(options, ""))
        {
        }

        private FusionAuthEntityTypePermission(string name, Input<string> id, FusionAuthEntityTypePermissionState? state = null, CustomResourceOptions? options = null)
            : base("fusionauth:index/fusionAuthEntityTypePermission:FusionAuthEntityTypePermission", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/theogravity/pulumi-fusionauth/releases/download/${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing FusionAuthEntityTypePermission resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static FusionAuthEntityTypePermission Get(string name, Input<string> id, FusionAuthEntityTypePermissionState? state = null, CustomResourceOptions? options = null)
        {
            return new FusionAuthEntityTypePermission(name, id, state, options);
        }
    }

    public sealed class FusionAuthEntityTypePermissionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// An object that can hold any information about the Permission that should be persisted. Must be a JSON string.
        /// </summary>
        [Input("data")]
        public Input<string>? Data { get; set; }

        /// <summary>
        /// The description of the Permission.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The Id of the Entity Type.
        /// </summary>
        [Input("entityTypeId", required: true)]
        public Input<string> EntityTypeId { get; set; } = null!;

        /// <summary>
        /// Whether or not the Permission is a default permission. A default permission is automatically granted to an entity of
        /// this type if no permissions are provided in a grant request.
        /// </summary>
        [Input("isDefault")]
        public Input<bool>? IsDefault { get; set; }

        /// <summary>
        /// The name of the Permission.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The Id to use for the new permission. If not specified a secure random UUID will be generated.
        /// </summary>
        [Input("permissionId")]
        public Input<string>? PermissionId { get; set; }

        public FusionAuthEntityTypePermissionArgs()
        {
        }
        public static new FusionAuthEntityTypePermissionArgs Empty => new FusionAuthEntityTypePermissionArgs();
    }

    public sealed class FusionAuthEntityTypePermissionState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// An object that can hold any information about the Permission that should be persisted. Must be a JSON string.
        /// </summary>
        [Input("data")]
        public Input<string>? Data { get; set; }

        /// <summary>
        /// The description of the Permission.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The Id of the Entity Type.
        /// </summary>
        [Input("entityTypeId")]
        public Input<string>? EntityTypeId { get; set; }

        /// <summary>
        /// Whether or not the Permission is a default permission. A default permission is automatically granted to an entity of
        /// this type if no permissions are provided in a grant request.
        /// </summary>
        [Input("isDefault")]
        public Input<bool>? IsDefault { get; set; }

        /// <summary>
        /// The name of the Permission.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The Id to use for the new permission. If not specified a secure random UUID will be generated.
        /// </summary>
        [Input("permissionId")]
        public Input<string>? PermissionId { get; set; }

        public FusionAuthEntityTypePermissionState()
        {
        }
        public static new FusionAuthEntityTypePermissionState Empty => new FusionAuthEntityTypePermissionState();
    }
}
