// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace theogravity.Fusionauth
{
    /// <summary>
    /// ## # Email Resource
    /// 
    /// This resource contains the APIs for managing Email Templates.
    /// 
    /// [Emails API](https://fusionauth.io/docs/v1/tech/apis/emails)
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.IO;
    /// using Pulumi;
    /// using Fusionauth = theogravity.Fusionauth;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var helloWorld = new Fusionauth.FusionAuthEMail("helloWorld", new()
    ///     {
    ///         DefaultFromName = "Welcome Team",
    ///         DefaultHtmlTemplate = File.ReadAllText($"{path.Module}/email_templates/HelloWorld.html.ftl"),
    ///         DefaultSubject = "Hello",
    ///         DefaultTextTemplate = File.ReadAllText($"{path.Module}/email_templates/HelloWorld.txt.ftl"),
    ///         FromEmail = "welcome@example.com.com",
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [FusionauthResourceType("fusionauth:index/fusionAuthEMail:FusionAuthEMail")]
    public partial class FusionAuthEMail : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The default From Name used when sending emails. If not provided, and a localized value cannot be determined, the default value for the tenant will be used. This is the display name part of the email address ( i.e. Jared Dunn &lt;jared@piedpiper.com&gt;).
        /// </summary>
        [Output("defaultFromName")]
        public Output<string> DefaultFromName { get; private set; } = null!;

        /// <summary>
        /// The default HTML Email Template.
        /// </summary>
        [Output("defaultHtmlTemplate")]
        public Output<string> DefaultHtmlTemplate { get; private set; } = null!;

        /// <summary>
        /// The default Subject used when sending emails.
        /// </summary>
        [Output("defaultSubject")]
        public Output<string> DefaultSubject { get; private set; } = null!;

        /// <summary>
        /// The default Text Email Template.
        /// </summary>
        [Output("defaultTextTemplate")]
        public Output<string> DefaultTextTemplate { get; private set; } = null!;

        /// <summary>
        /// The Id to use for the new Email Template. If not specified a secure random UUID will be generated.
        /// </summary>
        [Output("emailId")]
        public Output<string?> EmailId { get; private set; } = null!;

        /// <summary>
        /// The email address that this email will be sent from. If not provided, the default value for the tenant will be used. This is the address part email address (i.e. Jared Dunn &lt;jared@piedpiper.com&gt;).
        /// </summary>
        [Output("fromEmail")]
        public Output<string> FromEmail { get; private set; } = null!;

        /// <summary>
        /// The From Name used when sending emails to users who speak other languages. This overrides the default From Name based on the user’s list of preferred languages.
        /// </summary>
        [Output("localizedFromNames")]
        public Output<ImmutableDictionary<string, object>?> LocalizedFromNames { get; private set; } = null!;

        /// <summary>
        /// The HTML Email Template used when sending emails to users who speak other languages. This overrides the default HTML Email Template based on the user’s list of preferred languages.
        /// </summary>
        [Output("localizedHtmlTemplates")]
        public Output<ImmutableDictionary<string, object>?> LocalizedHtmlTemplates { get; private set; } = null!;

        /// <summary>
        /// The Subject used when sending emails to users who speak other languages. This overrides the default Subject based on the user’s list of preferred languages.
        /// </summary>
        [Output("localizedSubjects")]
        public Output<ImmutableDictionary<string, object>?> LocalizedSubjects { get; private set; } = null!;

        /// <summary>
        /// The Text Email Template used when sending emails to users who speak other languages. This overrides the default Text Email Template based on the user’s list of preferred languages.
        /// </summary>
        [Output("localizedTextTemplates")]
        public Output<ImmutableDictionary<string, object>?> LocalizedTextTemplates { get; private set; } = null!;

        /// <summary>
        /// A descriptive name for the email template (i.e. "April 2016 Coupon Email")
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;


        /// <summary>
        /// Create a FusionAuthEMail resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public FusionAuthEMail(string name, FusionAuthEMailArgs args, CustomResourceOptions? options = null)
            : base("fusionauth:index/fusionAuthEMail:FusionAuthEMail", name, args ?? new FusionAuthEMailArgs(), MakeResourceOptions(options, ""))
        {
        }

        private FusionAuthEMail(string name, Input<string> id, FusionAuthEMailState? state = null, CustomResourceOptions? options = null)
            : base("fusionauth:index/fusionAuthEMail:FusionAuthEMail", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/theogravity/pulumi-fusionauth/releases/download/v${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing FusionAuthEMail resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static FusionAuthEMail Get(string name, Input<string> id, FusionAuthEMailState? state = null, CustomResourceOptions? options = null)
        {
            return new FusionAuthEMail(name, id, state, options);
        }
    }

    public sealed class FusionAuthEMailArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The default From Name used when sending emails. If not provided, and a localized value cannot be determined, the default value for the tenant will be used. This is the display name part of the email address ( i.e. Jared Dunn &lt;jared@piedpiper.com&gt;).
        /// </summary>
        [Input("defaultFromName", required: true)]
        public Input<string> DefaultFromName { get; set; } = null!;

        /// <summary>
        /// The default HTML Email Template.
        /// </summary>
        [Input("defaultHtmlTemplate", required: true)]
        public Input<string> DefaultHtmlTemplate { get; set; } = null!;

        /// <summary>
        /// The default Subject used when sending emails.
        /// </summary>
        [Input("defaultSubject", required: true)]
        public Input<string> DefaultSubject { get; set; } = null!;

        /// <summary>
        /// The default Text Email Template.
        /// </summary>
        [Input("defaultTextTemplate", required: true)]
        public Input<string> DefaultTextTemplate { get; set; } = null!;

        /// <summary>
        /// The Id to use for the new Email Template. If not specified a secure random UUID will be generated.
        /// </summary>
        [Input("emailId")]
        public Input<string>? EmailId { get; set; }

        /// <summary>
        /// The email address that this email will be sent from. If not provided, the default value for the tenant will be used. This is the address part email address (i.e. Jared Dunn &lt;jared@piedpiper.com&gt;).
        /// </summary>
        [Input("fromEmail", required: true)]
        public Input<string> FromEmail { get; set; } = null!;

        [Input("localizedFromNames")]
        private InputMap<object>? _localizedFromNames;

        /// <summary>
        /// The From Name used when sending emails to users who speak other languages. This overrides the default From Name based on the user’s list of preferred languages.
        /// </summary>
        public InputMap<object> LocalizedFromNames
        {
            get => _localizedFromNames ?? (_localizedFromNames = new InputMap<object>());
            set => _localizedFromNames = value;
        }

        [Input("localizedHtmlTemplates")]
        private InputMap<object>? _localizedHtmlTemplates;

        /// <summary>
        /// The HTML Email Template used when sending emails to users who speak other languages. This overrides the default HTML Email Template based on the user’s list of preferred languages.
        /// </summary>
        public InputMap<object> LocalizedHtmlTemplates
        {
            get => _localizedHtmlTemplates ?? (_localizedHtmlTemplates = new InputMap<object>());
            set => _localizedHtmlTemplates = value;
        }

        [Input("localizedSubjects")]
        private InputMap<object>? _localizedSubjects;

        /// <summary>
        /// The Subject used when sending emails to users who speak other languages. This overrides the default Subject based on the user’s list of preferred languages.
        /// </summary>
        public InputMap<object> LocalizedSubjects
        {
            get => _localizedSubjects ?? (_localizedSubjects = new InputMap<object>());
            set => _localizedSubjects = value;
        }

        [Input("localizedTextTemplates")]
        private InputMap<object>? _localizedTextTemplates;

        /// <summary>
        /// The Text Email Template used when sending emails to users who speak other languages. This overrides the default Text Email Template based on the user’s list of preferred languages.
        /// </summary>
        public InputMap<object> LocalizedTextTemplates
        {
            get => _localizedTextTemplates ?? (_localizedTextTemplates = new InputMap<object>());
            set => _localizedTextTemplates = value;
        }

        /// <summary>
        /// A descriptive name for the email template (i.e. "April 2016 Coupon Email")
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public FusionAuthEMailArgs()
        {
        }
        public static new FusionAuthEMailArgs Empty => new FusionAuthEMailArgs();
    }

    public sealed class FusionAuthEMailState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The default From Name used when sending emails. If not provided, and a localized value cannot be determined, the default value for the tenant will be used. This is the display name part of the email address ( i.e. Jared Dunn &lt;jared@piedpiper.com&gt;).
        /// </summary>
        [Input("defaultFromName")]
        public Input<string>? DefaultFromName { get; set; }

        /// <summary>
        /// The default HTML Email Template.
        /// </summary>
        [Input("defaultHtmlTemplate")]
        public Input<string>? DefaultHtmlTemplate { get; set; }

        /// <summary>
        /// The default Subject used when sending emails.
        /// </summary>
        [Input("defaultSubject")]
        public Input<string>? DefaultSubject { get; set; }

        /// <summary>
        /// The default Text Email Template.
        /// </summary>
        [Input("defaultTextTemplate")]
        public Input<string>? DefaultTextTemplate { get; set; }

        /// <summary>
        /// The Id to use for the new Email Template. If not specified a secure random UUID will be generated.
        /// </summary>
        [Input("emailId")]
        public Input<string>? EmailId { get; set; }

        /// <summary>
        /// The email address that this email will be sent from. If not provided, the default value for the tenant will be used. This is the address part email address (i.e. Jared Dunn &lt;jared@piedpiper.com&gt;).
        /// </summary>
        [Input("fromEmail")]
        public Input<string>? FromEmail { get; set; }

        [Input("localizedFromNames")]
        private InputMap<object>? _localizedFromNames;

        /// <summary>
        /// The From Name used when sending emails to users who speak other languages. This overrides the default From Name based on the user’s list of preferred languages.
        /// </summary>
        public InputMap<object> LocalizedFromNames
        {
            get => _localizedFromNames ?? (_localizedFromNames = new InputMap<object>());
            set => _localizedFromNames = value;
        }

        [Input("localizedHtmlTemplates")]
        private InputMap<object>? _localizedHtmlTemplates;

        /// <summary>
        /// The HTML Email Template used when sending emails to users who speak other languages. This overrides the default HTML Email Template based on the user’s list of preferred languages.
        /// </summary>
        public InputMap<object> LocalizedHtmlTemplates
        {
            get => _localizedHtmlTemplates ?? (_localizedHtmlTemplates = new InputMap<object>());
            set => _localizedHtmlTemplates = value;
        }

        [Input("localizedSubjects")]
        private InputMap<object>? _localizedSubjects;

        /// <summary>
        /// The Subject used when sending emails to users who speak other languages. This overrides the default Subject based on the user’s list of preferred languages.
        /// </summary>
        public InputMap<object> LocalizedSubjects
        {
            get => _localizedSubjects ?? (_localizedSubjects = new InputMap<object>());
            set => _localizedSubjects = value;
        }

        [Input("localizedTextTemplates")]
        private InputMap<object>? _localizedTextTemplates;

        /// <summary>
        /// The Text Email Template used when sending emails to users who speak other languages. This overrides the default Text Email Template based on the user’s list of preferred languages.
        /// </summary>
        public InputMap<object> LocalizedTextTemplates
        {
            get => _localizedTextTemplates ?? (_localizedTextTemplates = new InputMap<object>());
            set => _localizedTextTemplates = value;
        }

        /// <summary>
        /// A descriptive name for the email template (i.e. "April 2016 Coupon Email")
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public FusionAuthEMailState()
        {
        }
        public static new FusionAuthEMailState Empty => new FusionAuthEMailState();
    }
}
