// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace theogravity.Fusionauth
{
    /// <summary>
    /// ## # Form Resource
    /// 
    /// A FusionAuth Form is a customizable object that contains one-to-many ordered steps. Each step is comprised of one or more Form Fields.
    /// 
    /// [Form API](https://fusionauth.io/docs/v1/tech/apis/forms/)
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using Pulumi;
    /// using Fusionauth = theogravity.Fusionauth;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var form = new Fusionauth.FusionAuthForm("form", new()
    ///     {
    ///         Data = 
    ///         {
    ///             { "description", "This form customizes the registration experience." },
    ///         },
    ///         Steps = new[]
    ///         {
    ///             new Fusionauth.Inputs.FusionAuthFormStepArgs
    ///             {
    ///                 Fields = new[]
    ///                 {
    ///                     "91909721-7d4f-b110-8f21-cfdee2a1edb8",
    ///                 },
    ///             },
    ///             new Fusionauth.Inputs.FusionAuthFormStepArgs
    ///             {
    ///                 Fields = new[]
    ///                 {
    ///                     "8ed89a31-c325-3156-72ed-6e89183af917",
    ///                     "a977cfd4-a9ed-c4cf-650f-f4539268ac38",
    ///                 },
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [FusionauthResourceType("fusionauth:index/fusionAuthForm:FusionAuthForm")]
    public partial class FusionAuthForm : global::Pulumi.CustomResource
    {
        /// <summary>
        /// An object that can hold any information about the Form Field that should be persisted.
        /// </summary>
        [Output("data")]
        public Output<ImmutableDictionary<string, object>?> Data { get; private set; } = null!;

        /// <summary>
        /// The Id to use for the new Form. If not specified a secure random UUID will be generated.
        /// </summary>
        [Output("formId")]
        public Output<string?> FormId { get; private set; } = null!;

        /// <summary>
        /// The unique name of the Form Field.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// An ordered list of objects containing one or more Form Fields. A Form must have at least one step defined.
        /// </summary>
        [Output("steps")]
        public Output<ImmutableArray<Outputs.FusionAuthFormStep>> Steps { get; private set; } = null!;

        /// <summary>
        /// The type of form being created, a form type cannot be changed after the form has been created.
        /// </summary>
        [Output("type")]
        public Output<string?> Type { get; private set; } = null!;


        /// <summary>
        /// Create a FusionAuthForm resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public FusionAuthForm(string name, FusionAuthFormArgs args, CustomResourceOptions? options = null)
            : base("fusionauth:index/fusionAuthForm:FusionAuthForm", name, args ?? new FusionAuthFormArgs(), MakeResourceOptions(options, ""))
        {
        }

        private FusionAuthForm(string name, Input<string> id, FusionAuthFormState? state = null, CustomResourceOptions? options = null)
            : base("fusionauth:index/fusionAuthForm:FusionAuthForm", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/theogravity/pulumi-fusionauth/releases/download/${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing FusionAuthForm resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static FusionAuthForm Get(string name, Input<string> id, FusionAuthFormState? state = null, CustomResourceOptions? options = null)
        {
            return new FusionAuthForm(name, id, state, options);
        }
    }

    public sealed class FusionAuthFormArgs : global::Pulumi.ResourceArgs
    {
        [Input("data")]
        private InputMap<object>? _data;

        /// <summary>
        /// An object that can hold any information about the Form Field that should be persisted.
        /// </summary>
        public InputMap<object> Data
        {
            get => _data ?? (_data = new InputMap<object>());
            set => _data = value;
        }

        /// <summary>
        /// The Id to use for the new Form. If not specified a secure random UUID will be generated.
        /// </summary>
        [Input("formId")]
        public Input<string>? FormId { get; set; }

        /// <summary>
        /// The unique name of the Form Field.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("steps", required: true)]
        private InputList<Inputs.FusionAuthFormStepArgs>? _steps;

        /// <summary>
        /// An ordered list of objects containing one or more Form Fields. A Form must have at least one step defined.
        /// </summary>
        public InputList<Inputs.FusionAuthFormStepArgs> Steps
        {
            get => _steps ?? (_steps = new InputList<Inputs.FusionAuthFormStepArgs>());
            set => _steps = value;
        }

        /// <summary>
        /// The type of form being created, a form type cannot be changed after the form has been created.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public FusionAuthFormArgs()
        {
        }
        public static new FusionAuthFormArgs Empty => new FusionAuthFormArgs();
    }

    public sealed class FusionAuthFormState : global::Pulumi.ResourceArgs
    {
        [Input("data")]
        private InputMap<object>? _data;

        /// <summary>
        /// An object that can hold any information about the Form Field that should be persisted.
        /// </summary>
        public InputMap<object> Data
        {
            get => _data ?? (_data = new InputMap<object>());
            set => _data = value;
        }

        /// <summary>
        /// The Id to use for the new Form. If not specified a secure random UUID will be generated.
        /// </summary>
        [Input("formId")]
        public Input<string>? FormId { get; set; }

        /// <summary>
        /// The unique name of the Form Field.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("steps")]
        private InputList<Inputs.FusionAuthFormStepGetArgs>? _steps;

        /// <summary>
        /// An ordered list of objects containing one or more Form Fields. A Form must have at least one step defined.
        /// </summary>
        public InputList<Inputs.FusionAuthFormStepGetArgs> Steps
        {
            get => _steps ?? (_steps = new InputList<Inputs.FusionAuthFormStepGetArgs>());
            set => _steps = value;
        }

        /// <summary>
        /// The type of form being created, a form type cannot be changed after the form has been created.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public FusionAuthFormState()
        {
        }
        public static new FusionAuthFormState Empty => new FusionAuthFormState();
    }
}
