// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace theogravity.Fusionauth
{
    /// <summary>
    /// ## # Entity Grant Resource
    /// 
    /// Entities can have Grants. Grants are relationships between a target Entity and one of two other types:
    /// 
    /// * A Recipient Entity
    /// * A User.
    /// 
    /// Grants can have zero or more Permissions associated with them.
    /// 
    /// [Entity Grant API](https://fusionauth.io/docs/v1/tech/apis/entity-management/grants)
    /// 
    /// ## Example Usage
    /// </summary>
    [FusionauthResourceType("fusionauth:index/fusionAuthEntityGrant:FusionAuthEntityGrant")]
    public partial class FusionAuthEntityGrant : global::Pulumi.CustomResource
    {
        /// <summary>
        /// An object that can hold any information about the Grant that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema.  Must be a JSON string.
        /// </summary>
        [Output("data")]
        public Output<string?> Data { get; private set; } = null!;

        /// <summary>
        /// The Id of the Entity to which access is granted.
        /// </summary>
        [Output("entityId")]
        public Output<string> EntityId { get; private set; } = null!;

        /// <summary>
        /// The set of permissions of this Grant.
        /// </summary>
        [Output("permissions")]
        public Output<ImmutableArray<string>> Permissions { get; private set; } = null!;

        /// <summary>
        /// The Entity Id for which access is granted. If `recipient_entity_id` is not provided, then the `user_id` will be required.
        /// </summary>
        [Output("recipientEntityId")]
        public Output<string?> RecipientEntityId { get; private set; } = null!;

        /// <summary>
        /// The unique Id of the tenant used to scope this API request.
        /// </summary>
        [Output("tenantId")]
        public Output<string> TenantId { get; private set; } = null!;

        /// <summary>
        /// The User Id for which access is granted. If `user_id` is not provided, then the `recipient_entity_id` will be required.
        /// </summary>
        [Output("userId")]
        public Output<string?> UserId { get; private set; } = null!;


        /// <summary>
        /// Create a FusionAuthEntityGrant resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public FusionAuthEntityGrant(string name, FusionAuthEntityGrantArgs args, CustomResourceOptions? options = null)
            : base("fusionauth:index/fusionAuthEntityGrant:FusionAuthEntityGrant", name, args ?? new FusionAuthEntityGrantArgs(), MakeResourceOptions(options, ""))
        {
        }

        private FusionAuthEntityGrant(string name, Input<string> id, FusionAuthEntityGrantState? state = null, CustomResourceOptions? options = null)
            : base("fusionauth:index/fusionAuthEntityGrant:FusionAuthEntityGrant", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/theogravity/pulumi-fusionauth/releases/download/${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing FusionAuthEntityGrant resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static FusionAuthEntityGrant Get(string name, Input<string> id, FusionAuthEntityGrantState? state = null, CustomResourceOptions? options = null)
        {
            return new FusionAuthEntityGrant(name, id, state, options);
        }
    }

    public sealed class FusionAuthEntityGrantArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// An object that can hold any information about the Grant that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema.  Must be a JSON string.
        /// </summary>
        [Input("data")]
        public Input<string>? Data { get; set; }

        /// <summary>
        /// The Id of the Entity to which access is granted.
        /// </summary>
        [Input("entityId", required: true)]
        public Input<string> EntityId { get; set; } = null!;

        [Input("permissions")]
        private InputList<string>? _permissions;

        /// <summary>
        /// The set of permissions of this Grant.
        /// </summary>
        public InputList<string> Permissions
        {
            get => _permissions ?? (_permissions = new InputList<string>());
            set => _permissions = value;
        }

        /// <summary>
        /// The Entity Id for which access is granted. If `recipient_entity_id` is not provided, then the `user_id` will be required.
        /// </summary>
        [Input("recipientEntityId")]
        public Input<string>? RecipientEntityId { get; set; }

        /// <summary>
        /// The unique Id of the tenant used to scope this API request.
        /// </summary>
        [Input("tenantId")]
        public Input<string>? TenantId { get; set; }

        /// <summary>
        /// The User Id for which access is granted. If `user_id` is not provided, then the `recipient_entity_id` will be required.
        /// </summary>
        [Input("userId")]
        public Input<string>? UserId { get; set; }

        public FusionAuthEntityGrantArgs()
        {
        }
        public static new FusionAuthEntityGrantArgs Empty => new FusionAuthEntityGrantArgs();
    }

    public sealed class FusionAuthEntityGrantState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// An object that can hold any information about the Grant that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema.  Must be a JSON string.
        /// </summary>
        [Input("data")]
        public Input<string>? Data { get; set; }

        /// <summary>
        /// The Id of the Entity to which access is granted.
        /// </summary>
        [Input("entityId")]
        public Input<string>? EntityId { get; set; }

        [Input("permissions")]
        private InputList<string>? _permissions;

        /// <summary>
        /// The set of permissions of this Grant.
        /// </summary>
        public InputList<string> Permissions
        {
            get => _permissions ?? (_permissions = new InputList<string>());
            set => _permissions = value;
        }

        /// <summary>
        /// The Entity Id for which access is granted. If `recipient_entity_id` is not provided, then the `user_id` will be required.
        /// </summary>
        [Input("recipientEntityId")]
        public Input<string>? RecipientEntityId { get; set; }

        /// <summary>
        /// The unique Id of the tenant used to scope this API request.
        /// </summary>
        [Input("tenantId")]
        public Input<string>? TenantId { get; set; }

        /// <summary>
        /// The User Id for which access is granted. If `user_id` is not provided, then the `recipient_entity_id` will be required.
        /// </summary>
        [Input("userId")]
        public Input<string>? UserId { get; set; }

        public FusionAuthEntityGrantState()
        {
        }
        public static new FusionAuthEntityGrantState Empty => new FusionAuthEntityGrantState();
    }
}
