// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace theogravity.Fusionauth.Outputs
{

    [OutputType]
    public sealed class FusionAuthTenantFormConfiguration
    {
        /// <summary>
        /// The unique Id of the form to use for the Add and Edit User form when used in the FusionAuth admin UI.
        /// </summary>
        public readonly string? AdminUserFormId;

        [OutputConstructor]
        private FusionAuthTenantFormConfiguration(string? adminUserFormId)
        {
            AdminUserFormId = adminUserFormId;
        }
    }
}
