// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace theogravity.Fusionauth.Outputs
{

    [OutputType]
    public sealed class FusionAuthApplicationCleanSpeakConfiguration
    {
        /// <summary>
        /// An array of UUIDs that map to the CleanSpeak applications for this Application. It is possible that a single Application in FusionAuth might have multiple Applications in CleanSpeak. For example, a FusionAuth Application for a game might have one CleanSpeak Application for usernames and another Application for chat.
        /// </summary>
        public readonly ImmutableArray<string> ApplicationIds;
        public readonly Outputs.FusionAuthApplicationCleanSpeakConfigurationUsernameModeration? UsernameModeration;

        [OutputConstructor]
        private FusionAuthApplicationCleanSpeakConfiguration(
            ImmutableArray<string> applicationIds,

            Outputs.FusionAuthApplicationCleanSpeakConfigurationUsernameModeration? usernameModeration)
        {
            ApplicationIds = applicationIds;
            UsernameModeration = usernameModeration;
        }
    }
}
