// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace theogravity.Fusionauth.Outputs
{

    [OutputType]
    public sealed class FusionAuthTenantMultiFactorConfigurationEmail
    {
        /// <summary>
        /// When enabled, users may utilize an email address to complete a multi-factor authentication request.
        /// </summary>
        public readonly bool? Enabled;
        /// <summary>
        /// The Id of the email template that is used when notifying a user to complete a multi-factor authentication request.
        /// </summary>
        public readonly string? TemplateId;

        [OutputConstructor]
        private FusionAuthTenantMultiFactorConfigurationEmail(
            bool? enabled,

            string? templateId)
        {
            Enabled = enabled;
            TemplateId = templateId;
        }
    }
}
