// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace theogravity.Fusionauth.Outputs
{

    [OutputType]
    public sealed class FusionAuthIdpSamlv2AssertionConfigurationDestination
    {
        /// <summary>
        /// The alternate destinations of the assertion.
        /// </summary>
        public readonly ImmutableArray<string> Alternates;
        /// <summary>
        /// The policy to use when performing a destination assertion on the SAML login request. The possible values are `Enabled`, `Disabled`, and `AllowAlternates`.
        /// </summary>
        public readonly string? Policy;

        [OutputConstructor]
        private FusionAuthIdpSamlv2AssertionConfigurationDestination(
            ImmutableArray<string> alternates,

            string? policy)
        {
            Alternates = alternates;
            Policy = policy;
        }
    }
}
