// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace theogravity.Fusionauth.Outputs
{

    [OutputType]
    public sealed class FusionAuthApplicationOauthConfiguration
    {
        /// <summary>
        /// An array of URLs that are the authorized origins for FusionAuth OAuth.
        /// </summary>
        public readonly ImmutableArray<string> AuthorizedOriginUrls;
        /// <summary>
        /// An array of URLs that are the authorized redirect URLs for FusionAuth OAuth.
        /// </summary>
        public readonly ImmutableArray<string> AuthorizedRedirectUrls;
        /// <summary>
        /// Determines whether wildcard expressions will be allowed in the authorized_redirect_urls and authorized_origin_urls.
        /// </summary>
        public readonly string? AuthorizedUrlValidationPolicy;
        /// <summary>
        /// Determines the client authentication requirements for the OAuth 2.0 Token endpoint.
        /// </summary>
        public readonly string? ClientAuthenticationPolicy;
        public readonly string? ClientId;
        /// <summary>
        /// The OAuth 2.0 client secret. If you leave this blank during a POST, a secure secret will be generated for you. If you leave this blank during PUT, the previous value will be maintained. For both POST and PUT you can provide a value and it will be stored.
        /// </summary>
        public readonly string? ClientSecret;
        /// <summary>
        /// Whether or not FusionAuth will log SAML debug messages to the event log. This is useful for debugging purposes.
        /// </summary>
        public readonly bool? Debug;
        /// <summary>
        /// The device verification URL to be used with the Device Code grant type, this field is required when device_code is enabled.
        /// </summary>
        public readonly string? DeviceVerificationUrl;
        /// <summary>
        /// The enabled grants for this application. In order to utilize a particular grant with the OAuth 2.0 endpoints you must have enabled the grant.
        /// </summary>
        public readonly ImmutableArray<string> EnabledGrants;
        /// <summary>
        /// Determines if the OAuth 2.0 Token endpoint will generate a refresh token when the offline_access scope is requested.
        /// </summary>
        public readonly bool? GenerateRefreshTokens;
        /// <summary>
        /// Behavior when /oauth2/logout is called.
        /// </summary>
        public readonly string? LogoutBehavior;
        /// <summary>
        /// The URL that the browser is taken to after the user logs out of the SAML service provider. Often service providers need this URL in order to correctly hook up single-logout. Note that FusionAuth does not support the SAML single-logout profile because most service providers to not support it properly.
        /// </summary>
        public readonly string? LogoutUrl;
        /// <summary>
        /// Determines the PKCE requirements when using the authorization code grant.
        /// </summary>
        public readonly string? ProofKeyForCodeExchangePolicy;
        /// <summary>
        /// Determines if the OAuth 2.0 Token endpoint requires client authentication. If this is enabled, the client must provide client credentials when using the Token endpoint. The client_id and client_secret may be provided using a Basic Authorization HTTP header, or by sending these parameters in the request body using POST data.
        /// </summary>
        public readonly bool? RequireClientAuthentication;
        /// <summary>
        /// When enabled the user will be required to be registered, or complete registration before redirecting to the configured callback in the authorization code grant or the implicit grant. This configuration does not currently apply to any other grant.
        /// </summary>
        public readonly bool? RequireRegistration;

        [OutputConstructor]
        private FusionAuthApplicationOauthConfiguration(
            ImmutableArray<string> authorizedOriginUrls,

            ImmutableArray<string> authorizedRedirectUrls,

            string? authorizedUrlValidationPolicy,

            string? clientAuthenticationPolicy,

            string? clientId,

            string? clientSecret,

            bool? debug,

            string? deviceVerificationUrl,

            ImmutableArray<string> enabledGrants,

            bool? generateRefreshTokens,

            string? logoutBehavior,

            string? logoutUrl,

            string? proofKeyForCodeExchangePolicy,

            bool? requireClientAuthentication,

            bool? requireRegistration)
        {
            AuthorizedOriginUrls = authorizedOriginUrls;
            AuthorizedRedirectUrls = authorizedRedirectUrls;
            AuthorizedUrlValidationPolicy = authorizedUrlValidationPolicy;
            ClientAuthenticationPolicy = clientAuthenticationPolicy;
            ClientId = clientId;
            ClientSecret = clientSecret;
            Debug = debug;
            DeviceVerificationUrl = deviceVerificationUrl;
            EnabledGrants = enabledGrants;
            GenerateRefreshTokens = generateRefreshTokens;
            LogoutBehavior = logoutBehavior;
            LogoutUrl = logoutUrl;
            ProofKeyForCodeExchangePolicy = proofKeyForCodeExchangePolicy;
            RequireClientAuthentication = requireClientAuthentication;
            RequireRegistration = requireRegistration;
        }
    }
}
