// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package fusionauth

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/theogravity/pulumi-fusionauth/sdk/go/fusionauth/internal"
)

// ## # Entity Grant Resource
//
// Entities can have Grants. Grants are relationships between a target Entity and one of two other types:
//
// * A Recipient Entity
// * A User.
//
// Grants can have zero or more Permissions associated with them.
//
// [Entity Grant API](https://fusionauth.io/docs/v1/tech/apis/entity-management/grants)
//
// ## Example Usage
type FusionAuthEntityGrant struct {
	pulumi.CustomResourceState

	// An object that can hold any information about the Grant that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema.  Must be a JSON string.
	Data pulumi.StringPtrOutput `pulumi:"data"`
	// The Id of the Entity to which access is granted.
	EntityId pulumi.StringOutput `pulumi:"entityId"`
	// The set of permissions of this Grant.
	Permissions pulumi.StringArrayOutput `pulumi:"permissions"`
	// The Entity Id for which access is granted. If `recipientEntityId` is not provided, then the `userId` will be required.
	RecipientEntityId pulumi.StringPtrOutput `pulumi:"recipientEntityId"`
	// The unique Id of the tenant used to scope this API request.
	TenantId pulumi.StringOutput `pulumi:"tenantId"`
	// The User Id for which access is granted. If `userId` is not provided, then the `recipientEntityId` will be required.
	UserId pulumi.StringPtrOutput `pulumi:"userId"`
}

// NewFusionAuthEntityGrant registers a new resource with the given unique name, arguments, and options.
func NewFusionAuthEntityGrant(ctx *pulumi.Context,
	name string, args *FusionAuthEntityGrantArgs, opts ...pulumi.ResourceOption) (*FusionAuthEntityGrant, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.EntityId == nil {
		return nil, errors.New("invalid value for required argument 'EntityId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource FusionAuthEntityGrant
	err := ctx.RegisterResource("fusionauth:index/fusionAuthEntityGrant:FusionAuthEntityGrant", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFusionAuthEntityGrant gets an existing FusionAuthEntityGrant resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFusionAuthEntityGrant(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FusionAuthEntityGrantState, opts ...pulumi.ResourceOption) (*FusionAuthEntityGrant, error) {
	var resource FusionAuthEntityGrant
	err := ctx.ReadResource("fusionauth:index/fusionAuthEntityGrant:FusionAuthEntityGrant", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering FusionAuthEntityGrant resources.
type fusionAuthEntityGrantState struct {
	// An object that can hold any information about the Grant that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema.  Must be a JSON string.
	Data *string `pulumi:"data"`
	// The Id of the Entity to which access is granted.
	EntityId *string `pulumi:"entityId"`
	// The set of permissions of this Grant.
	Permissions []string `pulumi:"permissions"`
	// The Entity Id for which access is granted. If `recipientEntityId` is not provided, then the `userId` will be required.
	RecipientEntityId *string `pulumi:"recipientEntityId"`
	// The unique Id of the tenant used to scope this API request.
	TenantId *string `pulumi:"tenantId"`
	// The User Id for which access is granted. If `userId` is not provided, then the `recipientEntityId` will be required.
	UserId *string `pulumi:"userId"`
}

type FusionAuthEntityGrantState struct {
	// An object that can hold any information about the Grant that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema.  Must be a JSON string.
	Data pulumi.StringPtrInput
	// The Id of the Entity to which access is granted.
	EntityId pulumi.StringPtrInput
	// The set of permissions of this Grant.
	Permissions pulumi.StringArrayInput
	// The Entity Id for which access is granted. If `recipientEntityId` is not provided, then the `userId` will be required.
	RecipientEntityId pulumi.StringPtrInput
	// The unique Id of the tenant used to scope this API request.
	TenantId pulumi.StringPtrInput
	// The User Id for which access is granted. If `userId` is not provided, then the `recipientEntityId` will be required.
	UserId pulumi.StringPtrInput
}

func (FusionAuthEntityGrantState) ElementType() reflect.Type {
	return reflect.TypeOf((*fusionAuthEntityGrantState)(nil)).Elem()
}

type fusionAuthEntityGrantArgs struct {
	// An object that can hold any information about the Grant that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema.  Must be a JSON string.
	Data *string `pulumi:"data"`
	// The Id of the Entity to which access is granted.
	EntityId string `pulumi:"entityId"`
	// The set of permissions of this Grant.
	Permissions []string `pulumi:"permissions"`
	// The Entity Id for which access is granted. If `recipientEntityId` is not provided, then the `userId` will be required.
	RecipientEntityId *string `pulumi:"recipientEntityId"`
	// The unique Id of the tenant used to scope this API request.
	TenantId *string `pulumi:"tenantId"`
	// The User Id for which access is granted. If `userId` is not provided, then the `recipientEntityId` will be required.
	UserId *string `pulumi:"userId"`
}

// The set of arguments for constructing a FusionAuthEntityGrant resource.
type FusionAuthEntityGrantArgs struct {
	// An object that can hold any information about the Grant that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema.  Must be a JSON string.
	Data pulumi.StringPtrInput
	// The Id of the Entity to which access is granted.
	EntityId pulumi.StringInput
	// The set of permissions of this Grant.
	Permissions pulumi.StringArrayInput
	// The Entity Id for which access is granted. If `recipientEntityId` is not provided, then the `userId` will be required.
	RecipientEntityId pulumi.StringPtrInput
	// The unique Id of the tenant used to scope this API request.
	TenantId pulumi.StringPtrInput
	// The User Id for which access is granted. If `userId` is not provided, then the `recipientEntityId` will be required.
	UserId pulumi.StringPtrInput
}

func (FusionAuthEntityGrantArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*fusionAuthEntityGrantArgs)(nil)).Elem()
}

type FusionAuthEntityGrantInput interface {
	pulumi.Input

	ToFusionAuthEntityGrantOutput() FusionAuthEntityGrantOutput
	ToFusionAuthEntityGrantOutputWithContext(ctx context.Context) FusionAuthEntityGrantOutput
}

func (*FusionAuthEntityGrant) ElementType() reflect.Type {
	return reflect.TypeOf((**FusionAuthEntityGrant)(nil)).Elem()
}

func (i *FusionAuthEntityGrant) ToFusionAuthEntityGrantOutput() FusionAuthEntityGrantOutput {
	return i.ToFusionAuthEntityGrantOutputWithContext(context.Background())
}

func (i *FusionAuthEntityGrant) ToFusionAuthEntityGrantOutputWithContext(ctx context.Context) FusionAuthEntityGrantOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FusionAuthEntityGrantOutput)
}

// FusionAuthEntityGrantArrayInput is an input type that accepts FusionAuthEntityGrantArray and FusionAuthEntityGrantArrayOutput values.
// You can construct a concrete instance of `FusionAuthEntityGrantArrayInput` via:
//
//	FusionAuthEntityGrantArray{ FusionAuthEntityGrantArgs{...} }
type FusionAuthEntityGrantArrayInput interface {
	pulumi.Input

	ToFusionAuthEntityGrantArrayOutput() FusionAuthEntityGrantArrayOutput
	ToFusionAuthEntityGrantArrayOutputWithContext(context.Context) FusionAuthEntityGrantArrayOutput
}

type FusionAuthEntityGrantArray []FusionAuthEntityGrantInput

func (FusionAuthEntityGrantArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FusionAuthEntityGrant)(nil)).Elem()
}

func (i FusionAuthEntityGrantArray) ToFusionAuthEntityGrantArrayOutput() FusionAuthEntityGrantArrayOutput {
	return i.ToFusionAuthEntityGrantArrayOutputWithContext(context.Background())
}

func (i FusionAuthEntityGrantArray) ToFusionAuthEntityGrantArrayOutputWithContext(ctx context.Context) FusionAuthEntityGrantArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FusionAuthEntityGrantArrayOutput)
}

// FusionAuthEntityGrantMapInput is an input type that accepts FusionAuthEntityGrantMap and FusionAuthEntityGrantMapOutput values.
// You can construct a concrete instance of `FusionAuthEntityGrantMapInput` via:
//
//	FusionAuthEntityGrantMap{ "key": FusionAuthEntityGrantArgs{...} }
type FusionAuthEntityGrantMapInput interface {
	pulumi.Input

	ToFusionAuthEntityGrantMapOutput() FusionAuthEntityGrantMapOutput
	ToFusionAuthEntityGrantMapOutputWithContext(context.Context) FusionAuthEntityGrantMapOutput
}

type FusionAuthEntityGrantMap map[string]FusionAuthEntityGrantInput

func (FusionAuthEntityGrantMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FusionAuthEntityGrant)(nil)).Elem()
}

func (i FusionAuthEntityGrantMap) ToFusionAuthEntityGrantMapOutput() FusionAuthEntityGrantMapOutput {
	return i.ToFusionAuthEntityGrantMapOutputWithContext(context.Background())
}

func (i FusionAuthEntityGrantMap) ToFusionAuthEntityGrantMapOutputWithContext(ctx context.Context) FusionAuthEntityGrantMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FusionAuthEntityGrantMapOutput)
}

type FusionAuthEntityGrantOutput struct{ *pulumi.OutputState }

func (FusionAuthEntityGrantOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FusionAuthEntityGrant)(nil)).Elem()
}

func (o FusionAuthEntityGrantOutput) ToFusionAuthEntityGrantOutput() FusionAuthEntityGrantOutput {
	return o
}

func (o FusionAuthEntityGrantOutput) ToFusionAuthEntityGrantOutputWithContext(ctx context.Context) FusionAuthEntityGrantOutput {
	return o
}

// An object that can hold any information about the Grant that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema.  Must be a JSON string.
func (o FusionAuthEntityGrantOutput) Data() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *FusionAuthEntityGrant) pulumi.StringPtrOutput { return v.Data }).(pulumi.StringPtrOutput)
}

// The Id of the Entity to which access is granted.
func (o FusionAuthEntityGrantOutput) EntityId() pulumi.StringOutput {
	return o.ApplyT(func(v *FusionAuthEntityGrant) pulumi.StringOutput { return v.EntityId }).(pulumi.StringOutput)
}

// The set of permissions of this Grant.
func (o FusionAuthEntityGrantOutput) Permissions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *FusionAuthEntityGrant) pulumi.StringArrayOutput { return v.Permissions }).(pulumi.StringArrayOutput)
}

// The Entity Id for which access is granted. If `recipientEntityId` is not provided, then the `userId` will be required.
func (o FusionAuthEntityGrantOutput) RecipientEntityId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *FusionAuthEntityGrant) pulumi.StringPtrOutput { return v.RecipientEntityId }).(pulumi.StringPtrOutput)
}

// The unique Id of the tenant used to scope this API request.
func (o FusionAuthEntityGrantOutput) TenantId() pulumi.StringOutput {
	return o.ApplyT(func(v *FusionAuthEntityGrant) pulumi.StringOutput { return v.TenantId }).(pulumi.StringOutput)
}

// The User Id for which access is granted. If `userId` is not provided, then the `recipientEntityId` will be required.
func (o FusionAuthEntityGrantOutput) UserId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *FusionAuthEntityGrant) pulumi.StringPtrOutput { return v.UserId }).(pulumi.StringPtrOutput)
}

type FusionAuthEntityGrantArrayOutput struct{ *pulumi.OutputState }

func (FusionAuthEntityGrantArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FusionAuthEntityGrant)(nil)).Elem()
}

func (o FusionAuthEntityGrantArrayOutput) ToFusionAuthEntityGrantArrayOutput() FusionAuthEntityGrantArrayOutput {
	return o
}

func (o FusionAuthEntityGrantArrayOutput) ToFusionAuthEntityGrantArrayOutputWithContext(ctx context.Context) FusionAuthEntityGrantArrayOutput {
	return o
}

func (o FusionAuthEntityGrantArrayOutput) Index(i pulumi.IntInput) FusionAuthEntityGrantOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *FusionAuthEntityGrant {
		return vs[0].([]*FusionAuthEntityGrant)[vs[1].(int)]
	}).(FusionAuthEntityGrantOutput)
}

type FusionAuthEntityGrantMapOutput struct{ *pulumi.OutputState }

func (FusionAuthEntityGrantMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FusionAuthEntityGrant)(nil)).Elem()
}

func (o FusionAuthEntityGrantMapOutput) ToFusionAuthEntityGrantMapOutput() FusionAuthEntityGrantMapOutput {
	return o
}

func (o FusionAuthEntityGrantMapOutput) ToFusionAuthEntityGrantMapOutputWithContext(ctx context.Context) FusionAuthEntityGrantMapOutput {
	return o
}

func (o FusionAuthEntityGrantMapOutput) MapIndex(k pulumi.StringInput) FusionAuthEntityGrantOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *FusionAuthEntityGrant {
		return vs[0].(map[string]*FusionAuthEntityGrant)[vs[1].(string)]
	}).(FusionAuthEntityGrantOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FusionAuthEntityGrantInput)(nil)).Elem(), &FusionAuthEntityGrant{})
	pulumi.RegisterInputType(reflect.TypeOf((*FusionAuthEntityGrantArrayInput)(nil)).Elem(), FusionAuthEntityGrantArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*FusionAuthEntityGrantMapInput)(nil)).Elem(), FusionAuthEntityGrantMap{})
	pulumi.RegisterOutputType(FusionAuthEntityGrantOutput{})
	pulumi.RegisterOutputType(FusionAuthEntityGrantArrayOutput{})
	pulumi.RegisterOutputType(FusionAuthEntityGrantMapOutput{})
}
