// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace theogravity.Fusionauth.Inputs
{

    public sealed class FusionAuthSystemConfigurationUiConfigurationArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// A hexadecimal color to override the default menu color in the user interface.
        /// </summary>
        [Input("headerColor")]
        public Input<string>? HeaderColor { get; set; }

        /// <summary>
        /// A URL of a logo to override the default FusionAuth logo in the user interface.
        /// </summary>
        [Input("logoUrl")]
        public Input<string>? LogoUrl { get; set; }

        /// <summary>
        /// A hexadecimal color to override the default menu font color in the user interface.
        /// </summary>
        [Input("menuFontColor")]
        public Input<string>? MenuFontColor { get; set; }

        public FusionAuthSystemConfigurationUiConfigurationArgs()
        {
        }
    }
}
