// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## # Entity Grant Resource
 *
 * Entities can have Grants. Grants are relationships between a target Entity and one of two other types:
 *
 * * A Recipient Entity
 * * A User.
 *
 * Grants can have zero or more Permissions associated with them.
 *
 * [Entity Grant API](https://fusionauth.io/docs/v1/tech/apis/entity-management/grants)
 *
 * ## Example Usage
 */
export class FusionAuthEntityGrant extends pulumi.CustomResource {
    /**
     * Get an existing FusionAuthEntityGrant resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FusionAuthEntityGrantState, opts?: pulumi.CustomResourceOptions): FusionAuthEntityGrant {
        return new FusionAuthEntityGrant(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'fusionauth:index/fusionAuthEntityGrant:FusionAuthEntityGrant';

    /**
     * Returns true if the given object is an instance of FusionAuthEntityGrant.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FusionAuthEntityGrant {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FusionAuthEntityGrant.__pulumiType;
    }

    /**
     * An object that can hold any information about the Grant that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema.  Must be a JSON string.
     */
    public readonly data!: pulumi.Output<string | undefined>;
    /**
     * The Id of the Entity to which access is granted.
     */
    public readonly entityId!: pulumi.Output<string>;
    /**
     * The set of permissions of this Grant.
     */
    public readonly permissions!: pulumi.Output<string[] | undefined>;
    /**
     * The Entity Id for which access is granted. If `recipientEntityId` is not provided, then the `userId` will be required.
     */
    public readonly recipientEntityId!: pulumi.Output<string | undefined>;
    /**
     * The unique Id of the tenant used to scope this API request.
     */
    public readonly tenantId!: pulumi.Output<string>;
    /**
     * The User Id for which access is granted. If `userId` is not provided, then the `recipientEntityId` will be required.
     */
    public readonly userId!: pulumi.Output<string | undefined>;

    /**
     * Create a FusionAuthEntityGrant resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FusionAuthEntityGrantArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FusionAuthEntityGrantArgs | FusionAuthEntityGrantState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FusionAuthEntityGrantState | undefined;
            resourceInputs["data"] = state ? state.data : undefined;
            resourceInputs["entityId"] = state ? state.entityId : undefined;
            resourceInputs["permissions"] = state ? state.permissions : undefined;
            resourceInputs["recipientEntityId"] = state ? state.recipientEntityId : undefined;
            resourceInputs["tenantId"] = state ? state.tenantId : undefined;
            resourceInputs["userId"] = state ? state.userId : undefined;
        } else {
            const args = argsOrState as FusionAuthEntityGrantArgs | undefined;
            if ((!args || args.entityId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'entityId'");
            }
            resourceInputs["data"] = args ? args.data : undefined;
            resourceInputs["entityId"] = args ? args.entityId : undefined;
            resourceInputs["permissions"] = args ? args.permissions : undefined;
            resourceInputs["recipientEntityId"] = args ? args.recipientEntityId : undefined;
            resourceInputs["tenantId"] = args ? args.tenantId : undefined;
            resourceInputs["userId"] = args ? args.userId : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(FusionAuthEntityGrant.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering FusionAuthEntityGrant resources.
 */
export interface FusionAuthEntityGrantState {
    /**
     * An object that can hold any information about the Grant that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema.  Must be a JSON string.
     */
    data?: pulumi.Input<string>;
    /**
     * The Id of the Entity to which access is granted.
     */
    entityId?: pulumi.Input<string>;
    /**
     * The set of permissions of this Grant.
     */
    permissions?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The Entity Id for which access is granted. If `recipientEntityId` is not provided, then the `userId` will be required.
     */
    recipientEntityId?: pulumi.Input<string>;
    /**
     * The unique Id of the tenant used to scope this API request.
     */
    tenantId?: pulumi.Input<string>;
    /**
     * The User Id for which access is granted. If `userId` is not provided, then the `recipientEntityId` will be required.
     */
    userId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a FusionAuthEntityGrant resource.
 */
export interface FusionAuthEntityGrantArgs {
    /**
     * An object that can hold any information about the Grant that should be persisted. Please review the limits on data field types as you plan for and build your custom data schema.  Must be a JSON string.
     */
    data?: pulumi.Input<string>;
    /**
     * The Id of the Entity to which access is granted.
     */
    entityId: pulumi.Input<string>;
    /**
     * The set of permissions of this Grant.
     */
    permissions?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The Entity Id for which access is granted. If `recipientEntityId` is not provided, then the `userId` will be required.
     */
    recipientEntityId?: pulumi.Input<string>;
    /**
     * The unique Id of the tenant used to scope this API request.
     */
    tenantId?: pulumi.Input<string>;
    /**
     * The User Id for which access is granted. If `userId` is not provided, then the `recipientEntityId` will be required.
     */
    userId?: pulumi.Input<string>;
}
