// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## # Theme Resource
 *
 * UI login themes can be configured to enable custom branding for your FusionAuth login workflow. Themes are configured per Tenant or optionally by Application.
 *
 * [Themes API](https://fusionauth.io/docs/v1/tech/apis/themes)
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as fusionauth from "pulumi-fusionauth";
 *
 * const mytheme = new fusionauth.FusionAuthTheme("mytheme", {
 *     accountEdit: "[#ftl/]",
 *     accountIndex: "[#ftl/]",
 *     accountTwoFactorDisable: "[#ftl/]",
 *     accountTwoFactorEnable: "[#ftl/]",
 *     accountTwoFactorIndex: "[#ftl/]",
 *     accountWebauthnAdd: "[#ftl/]",
 *     accountWebauthnDelete: "[#ftl/]",
 *     accountWebauthnIndex: "[#ftl/]",
 *     confirmationRequired: "[#ftl/]",
 *     defaultMessages: "[#ftl/]",
 *     emailComplete: "[#ftl/]",
 *     emailSend: "[#ftl/]",
 *     emailSent: "[#ftl/]",
 *     emailVerificationRequired: "[#ftl/]",
 *     emailVerify: "[#ftl/]",
 *     helpers: "[#ftl/]",
 *     index: "[#ftl/]",
 *     oauth2Authorize: "[#ftl/]",
 *     oauth2AuthorizedNotRegistered: "[#ftl/]",
 *     oauth2ChildRegistrationNotAllowed: "[#ftl/]",
 *     oauth2ChildRegistrationNotAllowedComplete: "[#ftl/]",
 *     oauth2CompleteRegistration: "[#ftl/]",
 *     oauth2Consent: "[#ftl/]",
 *     oauth2Device: "[#ftl/]",
 *     oauth2DeviceComplete: "[#ftl/]",
 *     oauth2Error: "[#ftl/]",
 *     oauth2Logout: "[#ftl/]",
 *     oauth2Passwordless: "[#ftl/]",
 *     oauth2Register: "[#ftl/]",
 *     oauth2StartIdpLink: "[#ftl/]",
 *     oauth2TwoFactor: "[#ftl/]",
 *     oauth2TwoFactorEnable: "[#ftl/]",
 *     oauth2TwoFactorEnableComplete: "[#ftl/]",
 *     oauth2TwoFactorMethods: "[#ftl/]",
 *     oauth2Wait: "[#ftl/]",
 *     oauth2Webauthn: "[#ftl/]",
 *     oauth2WebauthnReauth: "[#ftl/]",
 *     oauth2WebauthnReauthEnable: "[#ftl/]",
 *     passwordChange: "[#ftl/]",
 *     passwordComplete: "[#ftl/]",
 *     passwordForgot: "[#ftl/]",
 *     passwordSent: "[#ftl/]",
 *     registrationComplete: "[#ftl/]",
 *     registrationSend: "[#ftl/]",
 *     registrationSent: "[#ftl/]",
 *     registrationVerificationRequired: "[#ftl/]",
 *     registrationVerify: "[#ftl/]",
 *     samlv2Logout: "[#ftl/]",
 *     stylesheet: "/* stylish *&#47;",
 *     unauthorized: "[#ftl/]",
 * });
 * ```
 */
export class FusionAuthTheme extends pulumi.CustomResource {
    /**
     * Get an existing FusionAuthTheme resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FusionAuthThemeState, opts?: pulumi.CustomResourceOptions): FusionAuthTheme {
        return new FusionAuthTheme(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'fusionauth:index/fusionAuthTheme:FusionAuthTheme';

    /**
     * Returns true if the given object is an instance of FusionAuthTheme.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FusionAuthTheme {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FusionAuthTheme.__pulumiType;
    }

    /**
     * A FreeMarker template that is rendered when the user requests the /account/edit path. This page contains a form that enables authenticated users to update their profile.
     */
    public readonly accountEdit!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /account path. This is the self-service account landing page. An authenticated user may use this as a starting point for operations such as updating their profile or configuring multi-factor authentication.
     */
    public readonly accountIndex!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /account/two-factor/disable path. This page contains a form that accepts a verification code used to disable a multi-factor authentication method.
     */
    public readonly accountTwoFactorDisable!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /account/two-factor/enable path. This page contains a form that accepts a verification code used to enable a multi-factor authentication method. Additionally, this page contains presentation of recovery codes when a user enables multi-factor authentication for the first time.
     */
    public readonly accountTwoFactorEnable!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /account/two-factor path. This page displays an authenticated user’s configured multi-factor authentication methods. Additionally, it provides links to enable and disable a method.
     */
    public readonly accountTwoFactorIndex!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /account/webauthn/add path. This page contains a form that allows a user to register a new WebAuthn passkey.
     */
    public readonly accountWebauthnAdd!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /account/webauthn/delete path. This page contains a form that allows a user to delete a WebAuthn passkey.
     */
    public readonly accountWebauthnDelete!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /account/webauthn/ path. This page displays an authenticated user’s registered WebAuthn passkeys. Additionally, it provides links to delete an existing passkey and register a new passkey.
     */
    public readonly accountWebauthnIndex!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /confirmation-required path. This page is displayed when a user attempts to complete an email based workflow that did not begin in the same browser. For example, if the user starts a forgot password workflow, and then opens the link in a separate browser the user will be shown this panel.
     */
    public readonly confirmationRequired!: pulumi.Output<string>;
    /**
     * A properties file formatted String containing at least all of the message keys defined in the FusionAuth shipped messages file. 
     *
     * > **Note:** `defaultMessages` Is Required if not copying an existing Theme.
     */
    public readonly defaultMessages!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /email/complete path. This page is used after a user has verified their email address by clicking the URL in the email. After FusionAuth has updated their user object to indicate that their email was verified, the browser is redirected to this page.
     */
    public readonly emailComplete!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /email/send page. This page is used after a user has
     * asked for the verification email to be resent. This can happen if the URL in the email expired and the user clicked it.
     * In this case, the user can provide their email address again and FusionAuth will resend the email. After the user
     * submits their email and FusionAuth re-sends a verification email to them, the browser is redirected to this page.
     *
     * @deprecated Use emailSent instead. API endpoint has been migrated from /email/send to /email/sent.
     */
    public readonly emailSend!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /email/sent path. This page is used after a user has asked for the verification email to be resent. This can happen if the URL in the email expired and the user clicked it. In this case, the user can provide their email address again and FusionAuth will resend the email. After the user submits their email and FusionAuth re-sends a verification email to them, the browser is redirected to this page.
     */
    public readonly emailSent!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /email/verification-required path. This page is rendered when a user is required to verify their email address prior to being allowed to proceed with login. This occurs when Unverified behavior is set to Gated in email verification settings on the Tenant.
     */
    public readonly emailVerificationRequired!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /email/verify path. This page is rendered when a user clicks the URL from the verification email and the verificationId has expired. FusionAuth expires verificationId after a period of time (which is configurable). If the user has a URL from the verification email that has expired, this page will be rendered and the error will be displayed to the user.
     */
    public readonly emailVerify!: pulumi.Output<string>;
    /**
     * A FreeMarker template that contains all of the macros and templates used by the rest of the login Theme FreeMarker templates. This allows you to configure the general layout of your UI configuration and login theme without having to copy and paste HTML into each of the templates.
     */
    public readonly helpers!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the / path. This is the root landing page. This page is available to unauthenticated users and will be displayed whenever someone navigates to the FusionAuth host’s root page. Prior to version 1.27.0, navigating to this URL would redirect to /admin and would subsequently render the FusionAuth admin login page.
     */
    public readonly index!: pulumi.Output<string>;
    /**
     * A Map of localized versions of the messages. The key is the Locale and the value is a properties file formatted String.
     */
    public readonly localizedMessages!: pulumi.Output<{[key: string]: any} | undefined>;
    /**
     * A unique name for the Theme.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/authorize path. This is the main login page for FusionAuth and is used for all interactive OAuth2 and OpenID Connect workflows.
     */
    public readonly oauth2Authorize!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/authorized-not-registered path. This page is rendered when a user is not registered and the Application configuration requires registration before FusionAuth will complete the redirect.
     */
    public readonly oauth2AuthorizedNotRegistered!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/child-registration-not-allowed path. This page contains a form where a child must provide their parent’s email address to ask their parent to create an account for them in a Consent workflow.
     */
    public readonly oauth2ChildRegistrationNotAllowed!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/child-registration-not-allowed-complete path. This page is rendered is rendered after a child provides their parent’s email address for parental consent in a Consent workflow.
     */
    public readonly oauth2ChildRegistrationNotAllowedComplete!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/complete-registration path. This page contains a form that is used for users that have accounts but might be missing required fields.
     */
    public readonly oauth2CompleteRegistration!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when a third party application requests scopes from the user.
     */
    public readonly oauth2Consent!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/device path. This page contains a form for accepting an end user’s short code for the interactive portion of the OAuth Device Authorization Grant workflow.
     */
    public readonly oauth2Device!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/device-complete path. This page contains a complete message indicating the device authentication has completed.
     */
    public readonly oauth2DeviceComplete!: pulumi.Output<string>;
    /**
     * This page is used if the user starts or is in the middle of the OAuth workflow and any type of error occurs. This could be caused by the user messing with the URL or internally some type of information wasn’t passed between the OAuth endpoints correctly. For example, if you are federating login to an external IdP and that IdP does not properly echo the state parameter, FusionAuth’s OAuth workflow will break and this page will be displayed.
     */
    public readonly oauth2Error!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/logout page. This page is used if the user initiates a logout. This page causes the user to be logged out of all associated applications via a front-channel mechanism before being redirected.
     */
    public readonly oauth2Logout!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/passwordless path. This page is rendered when the user starts the passwordless login workflow. The page renders the form where the user types in their email address.
     */
    public readonly oauth2Passwordless!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/register path. This page is used to register or sign up the user for the application when self-service registration is enabled.
     */
    public readonly oauth2Register!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/start-idp-link path. This page is used if the Identity Provider is configured to have a pending link. The user is presented with the option to link their account with an existing FusionAuth user account.
     */
    public readonly oauth2StartIdpLink!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/two-factor path. This page is used if the user has two-factor authentication enabled and they need to type in their code again. FusionAuth will properly handle the processing on the back end. This page contains the form that the user will put their code into.
     */
    public readonly oauth2TwoFactor!: pulumi.Output<string>;
    /**
     * A FreeMarker template that contains the OAuth2 two-factor enable form.
     */
    public readonly oauth2TwoFactorEnable!: pulumi.Output<string>;
    /**
     * A FreeMarker template that contains the OAuth2 two-factor enable complete form.
     */
    public readonly oauth2TwoFactorEnableComplete!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/two-factor-methods path. This page contains a form providing a user with their configured multi-factor authentication options that they may use to complete the authentication challenge.
     */
    public readonly oauth2TwoFactorMethods!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/wait path. This page is rendered when FusionAuth is waiting for an external provider to complete an out of band authentication request. For example, during a HYPR login this page will be displayed until the user completes authentication.
     */
    public readonly oauth2Wait!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/webauthn path. This page contains a form where a user can enter their loginId (username or email address) to authenticate with one of their registered WebAuthn passkeys. This page uses the WebAuthn bootstrap workflow.
     */
    public readonly oauth2Webauthn!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/webauthn-reauth path. This page contains a form that lists the WebAuthn passkeys currently available for re-authentication. A user can select one of the listed passkeys to authenticate using the corresponding passkey and user account.
     */
    public readonly oauth2WebauthnReauth!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/webauthn-reauth-enable path. This page contains two forms. One allows the user to select one of their existing WebAuthn passkeys to use for re-authentication. The other allows the user to register a new WebAuthn passkey for re-authentication.
     */
    public readonly oauth2WebauthnReauthEnable!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /password/change path. This page is used if the user is required to change their password or if they have requested a password reset. This page contains the form that allows the user to provide a new password.
     */
    public readonly passwordChange!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /password/complete path. This page is used after the user has successfully updated their password, or reset it. This page should instruct the user that their password was updated and that they need to login again.
     */
    public readonly passwordComplete!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /password/forgot path. This page is used when a user starts the forgot password workflow. This page renders the form where the user types in their email address.
     */
    public readonly passwordForgot!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /password/sent path. This page is used when a user has submitted the forgot password form with their email. FusionAuth does not indicate back to the user if their email address was valid in order to prevent malicious activity that could reveal valid email addresses. Therefore, this page should indicate to the user that if their email was valid, they will receive an email shortly with a link to reset their password.
     */
    public readonly passwordSent!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /registration/complete path. This page is used after a user has verified their email address for a specific application (i.e. a user registration) by clicking the URL in the email. After FusionAuth has updated their registration object to indicate that their email was verified, the browser is redirected to this page.
     */
    public readonly registrationComplete!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /registration/send page. This page is used after a
     * user has asked for the application specific verification email to be resent. This can happen if the URL in the email
     * expired and the user clicked it. In this case, the user can provide their email address again and FusionAuth will resend
     * the email. After the user submits their email and FusionAuth re-sends a verification email to them, the browser is
     * redirected to this page.
     *
     * @deprecated Use registrationSent instead. API endpoint has been migrated from /registration/send to /registration/sent.
     */
    public readonly registrationSend!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /registration/sent path. This page is used after a user has asked for the application specific verification email to be resent. This can happen if the URL in the email expired and the user clicked it. In this case, the user can provide their email address again and FusionAuth will resend the email. After the user submits their email and FusionAuth re-sends a verification email to them, the browser is redirected to this page.
     */
    public readonly registrationSent!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /registration/verification-required path. This page is rendered when a user is required to verify their registration prior to being allowed to proceed with the registration flow. This occurs when Unverified behavior is set to Gated in registration verification settings on the Application.
     */
    public readonly registrationVerificationRequired!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /registration/verify path. This page is used when a user clicks the URL from the application specific verification email and the verificationId has expired. FusionAuth expires verificationId after a period of time (which is configurable). If the user has a URL from the verification email that has expired, this page will be rendered and the error will be displayed to the user.
     */
    public readonly registrationVerify!: pulumi.Output<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /samlv2/logout path. This page is used if the user initiates a SAML logout. This page causes the user to be logged out of all associated applications via a front-channel mechanism before being redirected.
     */
    public readonly samlv2Logout!: pulumi.Output<string>;
    /**
     * The optional Id of an existing Theme to make a copy of. If present, the defaultMessages, localizedMessages, templates, and stylesheet from the source Theme will be copied to the new Theme.
     */
    public readonly sourceThemeId!: pulumi.Output<string | undefined>;
    /**
     * A CSS stylesheet used to style the templates.
     */
    public readonly stylesheet!: pulumi.Output<string>;
    /**
     * An optional FreeMarker template that contains the unauthorized page.
     */
    public readonly unauthorized!: pulumi.Output<string>;

    /**
     * Create a FusionAuthTheme resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: FusionAuthThemeArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FusionAuthThemeArgs | FusionAuthThemeState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FusionAuthThemeState | undefined;
            resourceInputs["accountEdit"] = state ? state.accountEdit : undefined;
            resourceInputs["accountIndex"] = state ? state.accountIndex : undefined;
            resourceInputs["accountTwoFactorDisable"] = state ? state.accountTwoFactorDisable : undefined;
            resourceInputs["accountTwoFactorEnable"] = state ? state.accountTwoFactorEnable : undefined;
            resourceInputs["accountTwoFactorIndex"] = state ? state.accountTwoFactorIndex : undefined;
            resourceInputs["accountWebauthnAdd"] = state ? state.accountWebauthnAdd : undefined;
            resourceInputs["accountWebauthnDelete"] = state ? state.accountWebauthnDelete : undefined;
            resourceInputs["accountWebauthnIndex"] = state ? state.accountWebauthnIndex : undefined;
            resourceInputs["confirmationRequired"] = state ? state.confirmationRequired : undefined;
            resourceInputs["defaultMessages"] = state ? state.defaultMessages : undefined;
            resourceInputs["emailComplete"] = state ? state.emailComplete : undefined;
            resourceInputs["emailSend"] = state ? state.emailSend : undefined;
            resourceInputs["emailSent"] = state ? state.emailSent : undefined;
            resourceInputs["emailVerificationRequired"] = state ? state.emailVerificationRequired : undefined;
            resourceInputs["emailVerify"] = state ? state.emailVerify : undefined;
            resourceInputs["helpers"] = state ? state.helpers : undefined;
            resourceInputs["index"] = state ? state.index : undefined;
            resourceInputs["localizedMessages"] = state ? state.localizedMessages : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["oauth2Authorize"] = state ? state.oauth2Authorize : undefined;
            resourceInputs["oauth2AuthorizedNotRegistered"] = state ? state.oauth2AuthorizedNotRegistered : undefined;
            resourceInputs["oauth2ChildRegistrationNotAllowed"] = state ? state.oauth2ChildRegistrationNotAllowed : undefined;
            resourceInputs["oauth2ChildRegistrationNotAllowedComplete"] = state ? state.oauth2ChildRegistrationNotAllowedComplete : undefined;
            resourceInputs["oauth2CompleteRegistration"] = state ? state.oauth2CompleteRegistration : undefined;
            resourceInputs["oauth2Consent"] = state ? state.oauth2Consent : undefined;
            resourceInputs["oauth2Device"] = state ? state.oauth2Device : undefined;
            resourceInputs["oauth2DeviceComplete"] = state ? state.oauth2DeviceComplete : undefined;
            resourceInputs["oauth2Error"] = state ? state.oauth2Error : undefined;
            resourceInputs["oauth2Logout"] = state ? state.oauth2Logout : undefined;
            resourceInputs["oauth2Passwordless"] = state ? state.oauth2Passwordless : undefined;
            resourceInputs["oauth2Register"] = state ? state.oauth2Register : undefined;
            resourceInputs["oauth2StartIdpLink"] = state ? state.oauth2StartIdpLink : undefined;
            resourceInputs["oauth2TwoFactor"] = state ? state.oauth2TwoFactor : undefined;
            resourceInputs["oauth2TwoFactorEnable"] = state ? state.oauth2TwoFactorEnable : undefined;
            resourceInputs["oauth2TwoFactorEnableComplete"] = state ? state.oauth2TwoFactorEnableComplete : undefined;
            resourceInputs["oauth2TwoFactorMethods"] = state ? state.oauth2TwoFactorMethods : undefined;
            resourceInputs["oauth2Wait"] = state ? state.oauth2Wait : undefined;
            resourceInputs["oauth2Webauthn"] = state ? state.oauth2Webauthn : undefined;
            resourceInputs["oauth2WebauthnReauth"] = state ? state.oauth2WebauthnReauth : undefined;
            resourceInputs["oauth2WebauthnReauthEnable"] = state ? state.oauth2WebauthnReauthEnable : undefined;
            resourceInputs["passwordChange"] = state ? state.passwordChange : undefined;
            resourceInputs["passwordComplete"] = state ? state.passwordComplete : undefined;
            resourceInputs["passwordForgot"] = state ? state.passwordForgot : undefined;
            resourceInputs["passwordSent"] = state ? state.passwordSent : undefined;
            resourceInputs["registrationComplete"] = state ? state.registrationComplete : undefined;
            resourceInputs["registrationSend"] = state ? state.registrationSend : undefined;
            resourceInputs["registrationSent"] = state ? state.registrationSent : undefined;
            resourceInputs["registrationVerificationRequired"] = state ? state.registrationVerificationRequired : undefined;
            resourceInputs["registrationVerify"] = state ? state.registrationVerify : undefined;
            resourceInputs["samlv2Logout"] = state ? state.samlv2Logout : undefined;
            resourceInputs["sourceThemeId"] = state ? state.sourceThemeId : undefined;
            resourceInputs["stylesheet"] = state ? state.stylesheet : undefined;
            resourceInputs["unauthorized"] = state ? state.unauthorized : undefined;
        } else {
            const args = argsOrState as FusionAuthThemeArgs | undefined;
            resourceInputs["accountEdit"] = args ? args.accountEdit : undefined;
            resourceInputs["accountIndex"] = args ? args.accountIndex : undefined;
            resourceInputs["accountTwoFactorDisable"] = args ? args.accountTwoFactorDisable : undefined;
            resourceInputs["accountTwoFactorEnable"] = args ? args.accountTwoFactorEnable : undefined;
            resourceInputs["accountTwoFactorIndex"] = args ? args.accountTwoFactorIndex : undefined;
            resourceInputs["accountWebauthnAdd"] = args ? args.accountWebauthnAdd : undefined;
            resourceInputs["accountWebauthnDelete"] = args ? args.accountWebauthnDelete : undefined;
            resourceInputs["accountWebauthnIndex"] = args ? args.accountWebauthnIndex : undefined;
            resourceInputs["confirmationRequired"] = args ? args.confirmationRequired : undefined;
            resourceInputs["defaultMessages"] = args ? args.defaultMessages : undefined;
            resourceInputs["emailComplete"] = args ? args.emailComplete : undefined;
            resourceInputs["emailSend"] = args ? args.emailSend : undefined;
            resourceInputs["emailSent"] = args ? args.emailSent : undefined;
            resourceInputs["emailVerificationRequired"] = args ? args.emailVerificationRequired : undefined;
            resourceInputs["emailVerify"] = args ? args.emailVerify : undefined;
            resourceInputs["helpers"] = args ? args.helpers : undefined;
            resourceInputs["index"] = args ? args.index : undefined;
            resourceInputs["localizedMessages"] = args ? args.localizedMessages : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["oauth2Authorize"] = args ? args.oauth2Authorize : undefined;
            resourceInputs["oauth2AuthorizedNotRegistered"] = args ? args.oauth2AuthorizedNotRegistered : undefined;
            resourceInputs["oauth2ChildRegistrationNotAllowed"] = args ? args.oauth2ChildRegistrationNotAllowed : undefined;
            resourceInputs["oauth2ChildRegistrationNotAllowedComplete"] = args ? args.oauth2ChildRegistrationNotAllowedComplete : undefined;
            resourceInputs["oauth2CompleteRegistration"] = args ? args.oauth2CompleteRegistration : undefined;
            resourceInputs["oauth2Consent"] = args ? args.oauth2Consent : undefined;
            resourceInputs["oauth2Device"] = args ? args.oauth2Device : undefined;
            resourceInputs["oauth2DeviceComplete"] = args ? args.oauth2DeviceComplete : undefined;
            resourceInputs["oauth2Error"] = args ? args.oauth2Error : undefined;
            resourceInputs["oauth2Logout"] = args ? args.oauth2Logout : undefined;
            resourceInputs["oauth2Passwordless"] = args ? args.oauth2Passwordless : undefined;
            resourceInputs["oauth2Register"] = args ? args.oauth2Register : undefined;
            resourceInputs["oauth2StartIdpLink"] = args ? args.oauth2StartIdpLink : undefined;
            resourceInputs["oauth2TwoFactor"] = args ? args.oauth2TwoFactor : undefined;
            resourceInputs["oauth2TwoFactorEnable"] = args ? args.oauth2TwoFactorEnable : undefined;
            resourceInputs["oauth2TwoFactorEnableComplete"] = args ? args.oauth2TwoFactorEnableComplete : undefined;
            resourceInputs["oauth2TwoFactorMethods"] = args ? args.oauth2TwoFactorMethods : undefined;
            resourceInputs["oauth2Wait"] = args ? args.oauth2Wait : undefined;
            resourceInputs["oauth2Webauthn"] = args ? args.oauth2Webauthn : undefined;
            resourceInputs["oauth2WebauthnReauth"] = args ? args.oauth2WebauthnReauth : undefined;
            resourceInputs["oauth2WebauthnReauthEnable"] = args ? args.oauth2WebauthnReauthEnable : undefined;
            resourceInputs["passwordChange"] = args ? args.passwordChange : undefined;
            resourceInputs["passwordComplete"] = args ? args.passwordComplete : undefined;
            resourceInputs["passwordForgot"] = args ? args.passwordForgot : undefined;
            resourceInputs["passwordSent"] = args ? args.passwordSent : undefined;
            resourceInputs["registrationComplete"] = args ? args.registrationComplete : undefined;
            resourceInputs["registrationSend"] = args ? args.registrationSend : undefined;
            resourceInputs["registrationSent"] = args ? args.registrationSent : undefined;
            resourceInputs["registrationVerificationRequired"] = args ? args.registrationVerificationRequired : undefined;
            resourceInputs["registrationVerify"] = args ? args.registrationVerify : undefined;
            resourceInputs["samlv2Logout"] = args ? args.samlv2Logout : undefined;
            resourceInputs["sourceThemeId"] = args ? args.sourceThemeId : undefined;
            resourceInputs["stylesheet"] = args ? args.stylesheet : undefined;
            resourceInputs["unauthorized"] = args ? args.unauthorized : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(FusionAuthTheme.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering FusionAuthTheme resources.
 */
export interface FusionAuthThemeState {
    /**
     * A FreeMarker template that is rendered when the user requests the /account/edit path. This page contains a form that enables authenticated users to update their profile.
     */
    accountEdit?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /account path. This is the self-service account landing page. An authenticated user may use this as a starting point for operations such as updating their profile or configuring multi-factor authentication.
     */
    accountIndex?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /account/two-factor/disable path. This page contains a form that accepts a verification code used to disable a multi-factor authentication method.
     */
    accountTwoFactorDisable?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /account/two-factor/enable path. This page contains a form that accepts a verification code used to enable a multi-factor authentication method. Additionally, this page contains presentation of recovery codes when a user enables multi-factor authentication for the first time.
     */
    accountTwoFactorEnable?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /account/two-factor path. This page displays an authenticated user’s configured multi-factor authentication methods. Additionally, it provides links to enable and disable a method.
     */
    accountTwoFactorIndex?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /account/webauthn/add path. This page contains a form that allows a user to register a new WebAuthn passkey.
     */
    accountWebauthnAdd?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /account/webauthn/delete path. This page contains a form that allows a user to delete a WebAuthn passkey.
     */
    accountWebauthnDelete?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /account/webauthn/ path. This page displays an authenticated user’s registered WebAuthn passkeys. Additionally, it provides links to delete an existing passkey and register a new passkey.
     */
    accountWebauthnIndex?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /confirmation-required path. This page is displayed when a user attempts to complete an email based workflow that did not begin in the same browser. For example, if the user starts a forgot password workflow, and then opens the link in a separate browser the user will be shown this panel.
     */
    confirmationRequired?: pulumi.Input<string>;
    /**
     * A properties file formatted String containing at least all of the message keys defined in the FusionAuth shipped messages file. 
     *
     * > **Note:** `defaultMessages` Is Required if not copying an existing Theme.
     */
    defaultMessages?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /email/complete path. This page is used after a user has verified their email address by clicking the URL in the email. After FusionAuth has updated their user object to indicate that their email was verified, the browser is redirected to this page.
     */
    emailComplete?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /email/send page. This page is used after a user has
     * asked for the verification email to be resent. This can happen if the URL in the email expired and the user clicked it.
     * In this case, the user can provide their email address again and FusionAuth will resend the email. After the user
     * submits their email and FusionAuth re-sends a verification email to them, the browser is redirected to this page.
     *
     * @deprecated Use emailSent instead. API endpoint has been migrated from /email/send to /email/sent.
     */
    emailSend?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /email/sent path. This page is used after a user has asked for the verification email to be resent. This can happen if the URL in the email expired and the user clicked it. In this case, the user can provide their email address again and FusionAuth will resend the email. After the user submits their email and FusionAuth re-sends a verification email to them, the browser is redirected to this page.
     */
    emailSent?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /email/verification-required path. This page is rendered when a user is required to verify their email address prior to being allowed to proceed with login. This occurs when Unverified behavior is set to Gated in email verification settings on the Tenant.
     */
    emailVerificationRequired?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /email/verify path. This page is rendered when a user clicks the URL from the verification email and the verificationId has expired. FusionAuth expires verificationId after a period of time (which is configurable). If the user has a URL from the verification email that has expired, this page will be rendered and the error will be displayed to the user.
     */
    emailVerify?: pulumi.Input<string>;
    /**
     * A FreeMarker template that contains all of the macros and templates used by the rest of the login Theme FreeMarker templates. This allows you to configure the general layout of your UI configuration and login theme without having to copy and paste HTML into each of the templates.
     */
    helpers?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the / path. This is the root landing page. This page is available to unauthenticated users and will be displayed whenever someone navigates to the FusionAuth host’s root page. Prior to version 1.27.0, navigating to this URL would redirect to /admin and would subsequently render the FusionAuth admin login page.
     */
    index?: pulumi.Input<string>;
    /**
     * A Map of localized versions of the messages. The key is the Locale and the value is a properties file formatted String.
     */
    localizedMessages?: pulumi.Input<{[key: string]: any}>;
    /**
     * A unique name for the Theme.
     */
    name?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/authorize path. This is the main login page for FusionAuth and is used for all interactive OAuth2 and OpenID Connect workflows.
     */
    oauth2Authorize?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/authorized-not-registered path. This page is rendered when a user is not registered and the Application configuration requires registration before FusionAuth will complete the redirect.
     */
    oauth2AuthorizedNotRegistered?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/child-registration-not-allowed path. This page contains a form where a child must provide their parent’s email address to ask their parent to create an account for them in a Consent workflow.
     */
    oauth2ChildRegistrationNotAllowed?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/child-registration-not-allowed-complete path. This page is rendered is rendered after a child provides their parent’s email address for parental consent in a Consent workflow.
     */
    oauth2ChildRegistrationNotAllowedComplete?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/complete-registration path. This page contains a form that is used for users that have accounts but might be missing required fields.
     */
    oauth2CompleteRegistration?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when a third party application requests scopes from the user.
     */
    oauth2Consent?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/device path. This page contains a form for accepting an end user’s short code for the interactive portion of the OAuth Device Authorization Grant workflow.
     */
    oauth2Device?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/device-complete path. This page contains a complete message indicating the device authentication has completed.
     */
    oauth2DeviceComplete?: pulumi.Input<string>;
    /**
     * This page is used if the user starts or is in the middle of the OAuth workflow and any type of error occurs. This could be caused by the user messing with the URL or internally some type of information wasn’t passed between the OAuth endpoints correctly. For example, if you are federating login to an external IdP and that IdP does not properly echo the state parameter, FusionAuth’s OAuth workflow will break and this page will be displayed.
     */
    oauth2Error?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/logout page. This page is used if the user initiates a logout. This page causes the user to be logged out of all associated applications via a front-channel mechanism before being redirected.
     */
    oauth2Logout?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/passwordless path. This page is rendered when the user starts the passwordless login workflow. The page renders the form where the user types in their email address.
     */
    oauth2Passwordless?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/register path. This page is used to register or sign up the user for the application when self-service registration is enabled.
     */
    oauth2Register?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/start-idp-link path. This page is used if the Identity Provider is configured to have a pending link. The user is presented with the option to link their account with an existing FusionAuth user account.
     */
    oauth2StartIdpLink?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/two-factor path. This page is used if the user has two-factor authentication enabled and they need to type in their code again. FusionAuth will properly handle the processing on the back end. This page contains the form that the user will put their code into.
     */
    oauth2TwoFactor?: pulumi.Input<string>;
    /**
     * A FreeMarker template that contains the OAuth2 two-factor enable form.
     */
    oauth2TwoFactorEnable?: pulumi.Input<string>;
    /**
     * A FreeMarker template that contains the OAuth2 two-factor enable complete form.
     */
    oauth2TwoFactorEnableComplete?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/two-factor-methods path. This page contains a form providing a user with their configured multi-factor authentication options that they may use to complete the authentication challenge.
     */
    oauth2TwoFactorMethods?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/wait path. This page is rendered when FusionAuth is waiting for an external provider to complete an out of band authentication request. For example, during a HYPR login this page will be displayed until the user completes authentication.
     */
    oauth2Wait?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/webauthn path. This page contains a form where a user can enter their loginId (username or email address) to authenticate with one of their registered WebAuthn passkeys. This page uses the WebAuthn bootstrap workflow.
     */
    oauth2Webauthn?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/webauthn-reauth path. This page contains a form that lists the WebAuthn passkeys currently available for re-authentication. A user can select one of the listed passkeys to authenticate using the corresponding passkey and user account.
     */
    oauth2WebauthnReauth?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/webauthn-reauth-enable path. This page contains two forms. One allows the user to select one of their existing WebAuthn passkeys to use for re-authentication. The other allows the user to register a new WebAuthn passkey for re-authentication.
     */
    oauth2WebauthnReauthEnable?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /password/change path. This page is used if the user is required to change their password or if they have requested a password reset. This page contains the form that allows the user to provide a new password.
     */
    passwordChange?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /password/complete path. This page is used after the user has successfully updated their password, or reset it. This page should instruct the user that their password was updated and that they need to login again.
     */
    passwordComplete?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /password/forgot path. This page is used when a user starts the forgot password workflow. This page renders the form where the user types in their email address.
     */
    passwordForgot?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /password/sent path. This page is used when a user has submitted the forgot password form with their email. FusionAuth does not indicate back to the user if their email address was valid in order to prevent malicious activity that could reveal valid email addresses. Therefore, this page should indicate to the user that if their email was valid, they will receive an email shortly with a link to reset their password.
     */
    passwordSent?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /registration/complete path. This page is used after a user has verified their email address for a specific application (i.e. a user registration) by clicking the URL in the email. After FusionAuth has updated their registration object to indicate that their email was verified, the browser is redirected to this page.
     */
    registrationComplete?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /registration/send page. This page is used after a
     * user has asked for the application specific verification email to be resent. This can happen if the URL in the email
     * expired and the user clicked it. In this case, the user can provide their email address again and FusionAuth will resend
     * the email. After the user submits their email and FusionAuth re-sends a verification email to them, the browser is
     * redirected to this page.
     *
     * @deprecated Use registrationSent instead. API endpoint has been migrated from /registration/send to /registration/sent.
     */
    registrationSend?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /registration/sent path. This page is used after a user has asked for the application specific verification email to be resent. This can happen if the URL in the email expired and the user clicked it. In this case, the user can provide their email address again and FusionAuth will resend the email. After the user submits their email and FusionAuth re-sends a verification email to them, the browser is redirected to this page.
     */
    registrationSent?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /registration/verification-required path. This page is rendered when a user is required to verify their registration prior to being allowed to proceed with the registration flow. This occurs when Unverified behavior is set to Gated in registration verification settings on the Application.
     */
    registrationVerificationRequired?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /registration/verify path. This page is used when a user clicks the URL from the application specific verification email and the verificationId has expired. FusionAuth expires verificationId after a period of time (which is configurable). If the user has a URL from the verification email that has expired, this page will be rendered and the error will be displayed to the user.
     */
    registrationVerify?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /samlv2/logout path. This page is used if the user initiates a SAML logout. This page causes the user to be logged out of all associated applications via a front-channel mechanism before being redirected.
     */
    samlv2Logout?: pulumi.Input<string>;
    /**
     * The optional Id of an existing Theme to make a copy of. If present, the defaultMessages, localizedMessages, templates, and stylesheet from the source Theme will be copied to the new Theme.
     */
    sourceThemeId?: pulumi.Input<string>;
    /**
     * A CSS stylesheet used to style the templates.
     */
    stylesheet?: pulumi.Input<string>;
    /**
     * An optional FreeMarker template that contains the unauthorized page.
     */
    unauthorized?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a FusionAuthTheme resource.
 */
export interface FusionAuthThemeArgs {
    /**
     * A FreeMarker template that is rendered when the user requests the /account/edit path. This page contains a form that enables authenticated users to update their profile.
     */
    accountEdit?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /account path. This is the self-service account landing page. An authenticated user may use this as a starting point for operations such as updating their profile or configuring multi-factor authentication.
     */
    accountIndex?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /account/two-factor/disable path. This page contains a form that accepts a verification code used to disable a multi-factor authentication method.
     */
    accountTwoFactorDisable?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /account/two-factor/enable path. This page contains a form that accepts a verification code used to enable a multi-factor authentication method. Additionally, this page contains presentation of recovery codes when a user enables multi-factor authentication for the first time.
     */
    accountTwoFactorEnable?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /account/two-factor path. This page displays an authenticated user’s configured multi-factor authentication methods. Additionally, it provides links to enable and disable a method.
     */
    accountTwoFactorIndex?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /account/webauthn/add path. This page contains a form that allows a user to register a new WebAuthn passkey.
     */
    accountWebauthnAdd?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /account/webauthn/delete path. This page contains a form that allows a user to delete a WebAuthn passkey.
     */
    accountWebauthnDelete?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /account/webauthn/ path. This page displays an authenticated user’s registered WebAuthn passkeys. Additionally, it provides links to delete an existing passkey and register a new passkey.
     */
    accountWebauthnIndex?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /confirmation-required path. This page is displayed when a user attempts to complete an email based workflow that did not begin in the same browser. For example, if the user starts a forgot password workflow, and then opens the link in a separate browser the user will be shown this panel.
     */
    confirmationRequired?: pulumi.Input<string>;
    /**
     * A properties file formatted String containing at least all of the message keys defined in the FusionAuth shipped messages file. 
     *
     * > **Note:** `defaultMessages` Is Required if not copying an existing Theme.
     */
    defaultMessages?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /email/complete path. This page is used after a user has verified their email address by clicking the URL in the email. After FusionAuth has updated their user object to indicate that their email was verified, the browser is redirected to this page.
     */
    emailComplete?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /email/send page. This page is used after a user has
     * asked for the verification email to be resent. This can happen if the URL in the email expired and the user clicked it.
     * In this case, the user can provide their email address again and FusionAuth will resend the email. After the user
     * submits their email and FusionAuth re-sends a verification email to them, the browser is redirected to this page.
     *
     * @deprecated Use emailSent instead. API endpoint has been migrated from /email/send to /email/sent.
     */
    emailSend?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /email/sent path. This page is used after a user has asked for the verification email to be resent. This can happen if the URL in the email expired and the user clicked it. In this case, the user can provide their email address again and FusionAuth will resend the email. After the user submits their email and FusionAuth re-sends a verification email to them, the browser is redirected to this page.
     */
    emailSent?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /email/verification-required path. This page is rendered when a user is required to verify their email address prior to being allowed to proceed with login. This occurs when Unverified behavior is set to Gated in email verification settings on the Tenant.
     */
    emailVerificationRequired?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /email/verify path. This page is rendered when a user clicks the URL from the verification email and the verificationId has expired. FusionAuth expires verificationId after a period of time (which is configurable). If the user has a URL from the verification email that has expired, this page will be rendered and the error will be displayed to the user.
     */
    emailVerify?: pulumi.Input<string>;
    /**
     * A FreeMarker template that contains all of the macros and templates used by the rest of the login Theme FreeMarker templates. This allows you to configure the general layout of your UI configuration and login theme without having to copy and paste HTML into each of the templates.
     */
    helpers?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the / path. This is the root landing page. This page is available to unauthenticated users and will be displayed whenever someone navigates to the FusionAuth host’s root page. Prior to version 1.27.0, navigating to this URL would redirect to /admin and would subsequently render the FusionAuth admin login page.
     */
    index?: pulumi.Input<string>;
    /**
     * A Map of localized versions of the messages. The key is the Locale and the value is a properties file formatted String.
     */
    localizedMessages?: pulumi.Input<{[key: string]: any}>;
    /**
     * A unique name for the Theme.
     */
    name?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/authorize path. This is the main login page for FusionAuth and is used for all interactive OAuth2 and OpenID Connect workflows.
     */
    oauth2Authorize?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/authorized-not-registered path. This page is rendered when a user is not registered and the Application configuration requires registration before FusionAuth will complete the redirect.
     */
    oauth2AuthorizedNotRegistered?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/child-registration-not-allowed path. This page contains a form where a child must provide their parent’s email address to ask their parent to create an account for them in a Consent workflow.
     */
    oauth2ChildRegistrationNotAllowed?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/child-registration-not-allowed-complete path. This page is rendered is rendered after a child provides their parent’s email address for parental consent in a Consent workflow.
     */
    oauth2ChildRegistrationNotAllowedComplete?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/complete-registration path. This page contains a form that is used for users that have accounts but might be missing required fields.
     */
    oauth2CompleteRegistration?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when a third party application requests scopes from the user.
     */
    oauth2Consent?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/device path. This page contains a form for accepting an end user’s short code for the interactive portion of the OAuth Device Authorization Grant workflow.
     */
    oauth2Device?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/device-complete path. This page contains a complete message indicating the device authentication has completed.
     */
    oauth2DeviceComplete?: pulumi.Input<string>;
    /**
     * This page is used if the user starts or is in the middle of the OAuth workflow and any type of error occurs. This could be caused by the user messing with the URL or internally some type of information wasn’t passed between the OAuth endpoints correctly. For example, if you are federating login to an external IdP and that IdP does not properly echo the state parameter, FusionAuth’s OAuth workflow will break and this page will be displayed.
     */
    oauth2Error?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/logout page. This page is used if the user initiates a logout. This page causes the user to be logged out of all associated applications via a front-channel mechanism before being redirected.
     */
    oauth2Logout?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/passwordless path. This page is rendered when the user starts the passwordless login workflow. The page renders the form where the user types in their email address.
     */
    oauth2Passwordless?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/register path. This page is used to register or sign up the user for the application when self-service registration is enabled.
     */
    oauth2Register?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/start-idp-link path. This page is used if the Identity Provider is configured to have a pending link. The user is presented with the option to link their account with an existing FusionAuth user account.
     */
    oauth2StartIdpLink?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/two-factor path. This page is used if the user has two-factor authentication enabled and they need to type in their code again. FusionAuth will properly handle the processing on the back end. This page contains the form that the user will put their code into.
     */
    oauth2TwoFactor?: pulumi.Input<string>;
    /**
     * A FreeMarker template that contains the OAuth2 two-factor enable form.
     */
    oauth2TwoFactorEnable?: pulumi.Input<string>;
    /**
     * A FreeMarker template that contains the OAuth2 two-factor enable complete form.
     */
    oauth2TwoFactorEnableComplete?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/two-factor-methods path. This page contains a form providing a user with their configured multi-factor authentication options that they may use to complete the authentication challenge.
     */
    oauth2TwoFactorMethods?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/wait path. This page is rendered when FusionAuth is waiting for an external provider to complete an out of band authentication request. For example, during a HYPR login this page will be displayed until the user completes authentication.
     */
    oauth2Wait?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/webauthn path. This page contains a form where a user can enter their loginId (username or email address) to authenticate with one of their registered WebAuthn passkeys. This page uses the WebAuthn bootstrap workflow.
     */
    oauth2Webauthn?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/webauthn-reauth path. This page contains a form that lists the WebAuthn passkeys currently available for re-authentication. A user can select one of the listed passkeys to authenticate using the corresponding passkey and user account.
     */
    oauth2WebauthnReauth?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /oauth2/webauthn-reauth-enable path. This page contains two forms. One allows the user to select one of their existing WebAuthn passkeys to use for re-authentication. The other allows the user to register a new WebAuthn passkey for re-authentication.
     */
    oauth2WebauthnReauthEnable?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /password/change path. This page is used if the user is required to change their password or if they have requested a password reset. This page contains the form that allows the user to provide a new password.
     */
    passwordChange?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /password/complete path. This page is used after the user has successfully updated their password, or reset it. This page should instruct the user that their password was updated and that they need to login again.
     */
    passwordComplete?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /password/forgot path. This page is used when a user starts the forgot password workflow. This page renders the form where the user types in their email address.
     */
    passwordForgot?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /password/sent path. This page is used when a user has submitted the forgot password form with their email. FusionAuth does not indicate back to the user if their email address was valid in order to prevent malicious activity that could reveal valid email addresses. Therefore, this page should indicate to the user that if their email was valid, they will receive an email shortly with a link to reset their password.
     */
    passwordSent?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /registration/complete path. This page is used after a user has verified their email address for a specific application (i.e. a user registration) by clicking the URL in the email. After FusionAuth has updated their registration object to indicate that their email was verified, the browser is redirected to this page.
     */
    registrationComplete?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /registration/send page. This page is used after a
     * user has asked for the application specific verification email to be resent. This can happen if the URL in the email
     * expired and the user clicked it. In this case, the user can provide their email address again and FusionAuth will resend
     * the email. After the user submits their email and FusionAuth re-sends a verification email to them, the browser is
     * redirected to this page.
     *
     * @deprecated Use registrationSent instead. API endpoint has been migrated from /registration/send to /registration/sent.
     */
    registrationSend?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /registration/sent path. This page is used after a user has asked for the application specific verification email to be resent. This can happen if the URL in the email expired and the user clicked it. In this case, the user can provide their email address again and FusionAuth will resend the email. After the user submits their email and FusionAuth re-sends a verification email to them, the browser is redirected to this page.
     */
    registrationSent?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /registration/verification-required path. This page is rendered when a user is required to verify their registration prior to being allowed to proceed with the registration flow. This occurs when Unverified behavior is set to Gated in registration verification settings on the Application.
     */
    registrationVerificationRequired?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /registration/verify path. This page is used when a user clicks the URL from the application specific verification email and the verificationId has expired. FusionAuth expires verificationId after a period of time (which is configurable). If the user has a URL from the verification email that has expired, this page will be rendered and the error will be displayed to the user.
     */
    registrationVerify?: pulumi.Input<string>;
    /**
     * A FreeMarker template that is rendered when the user requests the /samlv2/logout path. This page is used if the user initiates a SAML logout. This page causes the user to be logged out of all associated applications via a front-channel mechanism before being redirected.
     */
    samlv2Logout?: pulumi.Input<string>;
    /**
     * The optional Id of an existing Theme to make a copy of. If present, the defaultMessages, localizedMessages, templates, and stylesheet from the source Theme will be copied to the new Theme.
     */
    sourceThemeId?: pulumi.Input<string>;
    /**
     * A CSS stylesheet used to style the templates.
     */
    stylesheet?: pulumi.Input<string>;
    /**
     * An optional FreeMarker template that contains the unauthorized page.
     */
    unauthorized?: pulumi.Input<string>;
}
